# Generated by Django 2.2 on 2019-05-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('qualidade', models.CharField(max_length=100)),
                ('defeito', models.CharField(default='não está comigo', max_length=100)),
                ('reciproco', models.BooleanField(default=False)),
                ('signo', models.CharField(choices=[('ar', 'áries'), ('tr', 'touro'), ('gm', 'gêmeos'), ('cr', 'câncer'), ('le', 'leão'), ('vr', 'virgem'), ('lb', 'libra'), ('es', 'escorpião'), ('sg', 'sagitário'), ('cp', 'capricórnio'), ('aq', 'aquário'), ('px', 'peixes')], max_length=2)),
                ('solteiro', models.BooleanField(default=False)),
            ],
        ),
    ]
